### ISSUE TITLE
bug comand

### ISSUE THREAD

**Issue by techwiz37** [RC047/Kuhong-V4#11]
jika ngechat orang di w bot. tabrakan dengan comand yang responnya Perintah ini hanya dapat digunakan di grup!
![Screenshot_2021-04-01-17-22-37-175_com whatsapp w4b](https://user-images.githubusercontent.com/73012169/113280802-fe49b280-930e-11eb-99f3-1058b687eb1d.jpg)

**Comment by techwiz37** [comment]
![Screenshot_2021-04-01-17-25-08-973_com whatsapp w4b](https://user-images.githubusercontent.com/73012169/113281005-3e109a00-930f-11eb-957b-f1343d320c27.jpg)

ini bug? bikin sw sendiri

**Comment by elssword** [comment]
Sw masuk ke @statusbroadcast jadi gk tau kenapa kehitung user kalo ada yg delete sw kadang fitur delete aktif wkwk

**Comment by RC047** [comment]
Yg antidelete emg gitu,, klo mau dioffin ketik disw commandnya !enable delete
