### ISSUE TITLE
req

### ISSUE THREAD

**Issue by techwiz37** [RC047/Kuhong-V4#12]
req um,database nya bikinin tambahan saldo
jadi
exp,
limit,
saldo,
aku nyoba add sendiri malah ngeror expnya 😂

**Comment by techwiz37** [comment]
saldonya sistemnya kyk limit aja bg, niatnya mau bkin saldo didapatkan dari beli via pulsa/dana
gunanya nanti saldo itu mau kubuat fitur isi pulsa paket data saldo emey vouchergame dll

**Comment by elssword** [comment]
Tambahin aja 
if (!isNumber(user.uang)) user.uang = 0
Sama
uang: 0,
Di handler js

**Comment by techwiz37** [comment]
oh itu aja?

**Comment by elssword** [comment]
Iya

**Comment by elssword** [comment]
Kalo bener bener mau kayak limit tambahin
if (!isPrems && plugin.uang && global.DATABASE._data.users[m.sender].uanh < plugin.uang
            this.reply(m.chat, `saldo anda habis, silahkan beli melalui *${usedPrefix}atm*`, m)
            continue // uang habis

**Comment by RC047** [comment]
isu terpecahkan
