### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ardisuro997** [RC047/Kuhong-V4#13]
Ngab, cara matiin antilink gmn? Dah w ketik #disable antilink udh ada notif, trus w coba share link tetep ke kick, trus masalahnya admin group pun bisa kena kick, cara atasinye gmn?:v

**Comment by elssword** [comment]
Hmm

**Comment by elssword** [comment]
Tambahin
if (chat.antiLink) {.......
.........}

**Comment by elssword** [comment]
Udah bang di pull request cek aja

**Comment by RC047** [comment]
Nnti w buat versi gw aja,, soalnya klo yg dri nrtm gk bisa ngedetek diversi bot w :v
