### ISSUE TITLE
Hai, Bagaimana cara membuat sticker triggered berfungsi di plugin.js?

### ISSUE THREAD

**Issue by prioprastyo** [RC047/Kuhong-V4#17]
if ((isMedia && !mek.message.videoMessage || isQuotedImage) && args.length == 0) {
				           ger = isQuotedImage ? JSON.parse(JSON.stringify(mek).replace('quotedM','m')).message.extendedTextMessage.contextInfo : mek
				           reply(ind.wait())
						var imgbb = require('imgbb-uploader')
				         owgi = await client.downloadAndSaveMediaMessage(ger)
				           anu = await imgbb("08579d070df9a07cb1c2ee565aece767", owgi)
				        teks = `${anu.display_url}`
				         ranp = getRandom('.gif')
				        rano = getRandom('.webp')
				        anu1 = `https://some-random-api.ml/canvas/triggered?avatar=${teks}`
				       exec(`wget ${anu1} -O ${ranp} && ffmpeg -i ${ranp} -vcodec libwebp -filter:v fps=fps=20 -lossless 1 -loop 0 -preset default -an -vsync 0 -s 512:512 ${rano}`, (err) => {
                        fs.unlinkSync(ranp)
                        if (err) return reply(imd.stikga())
                        nobg = fs.readFileSync(rano)
                        client.sendMessage(from, nobg, sticker, {quoted: mek})
                        fs.unlinkSync(rano)
                })

**Comment by prioprastyo** [comment]
Aku dapet itu dari sc bot lain, tadinya mau aku salin :(
Tapi gabisa...

**Comment by RC047** [comment]
Beda script,, tinggal harus bisa ngekonvertnya aja

**Comment by prioprastyo** [comment]
Bagaimana caranya?, Aku gak tau itu, aku nyoba menyalin  script wasted.js menjadi triggered.js tapi gak kedeteksi di sananya

Caranya biar ke deteksi bagaimana?, Padahal hanya mengganti urlnya saja sama command.

**Comment by RC047** [comment]
Searching aja,, klo disini bnyk ngetik males ketik (:
