### ISSUE TITLE
npm install eror

### ISSUE THREAD

**Issue by techwiz37** [RC047/Kuhong-V4#18]
responnya
$ npm install
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2021-04-08T23_37_30_621Z-debug.log

**Comment by RC047** [comment]
Itu terjadi biasanya gara2 pindah versi dri node_modules,, cara pling efektif sih yaa reset termuxnya ;v
