### ISSUE TITLE
cara nambahin pitur kek mana ya? Cuman nanya:v

### ISSUE THREAD

**Issue by KazukoGans** [RC047/Kuhong-V4#19]

**Comment by RC047** [comment]
Buat file kasih nama diujungnya .js (nama.js) terus isi kodenya

**Comment by KazukoGans** [comment]
Kok pada saat w ketik module expor kok error?

**Comment by KazukoGans** [comment]
> Buat file kasih nama diujungnya .js (nama.js) terus isi kodenya

.

**Comment by KazukoGans** [comment]
> Kok pada saat w ketik module expor kok error?

.

**Comment by RC047** [comment]
module.exports = handler

**Comment by KazukoGans** [comment]
> module.exports = handler

Dh w ketik tapi error pas mo nyalain bot

**Comment by RC047** [comment]
ss

**Comment by JereGanz342** [comment]
hy
