### ISSUE TITLE
AntilinkGoogle

### ISSUE THREAD

**Issue by lilnext01** [RC047/Kuhong-V4#2]
Bagaimana cara mendapatkan Antilinks dari situs lain juga? dan bukan hanya Whatsapp. Saya mencoba ini, tetapi tidak berhasil

**Comment by lilnext01** [comment]
let handler = async function(m, { conn , args, isAdmin, isBotAdmin }) {

  let who = m.mentionedJid && m.mentionedJid[0] ? m.mentionedJid[0] : m.fromMe ? conn.user.jid : m.sender
  let username = conn.getName(who)
  let mentionedJid = [m.sender]
  let name = m.fromMe ? conn.user : conn.contacts[m.sender]
  let users = m.sender

    conn.reply(m.chat, `Foi detectado um link de *Google* enviado por *${username}*\nDssculpe, mas você será banido deste grupo.`, m)
 await conn.groupRemove(m.chat, [users])
}
handler.tags = ['group']
handler.customPrefix = /www.google.com/\/([0-9A-Za-z]{20,24})/i
handler.command = new RegExp
handler.group = true

handler.admin = false
handler.botAdmin = true

handler.fail = null

module.exports = handler

**Comment by RC047** [comment]
> 
> 
> let handler = async function(m, { conn , args, isAdmin, isBotAdmin }) {
> 
> let who = m.mentionedJid && m.mentionedJid[0] ? m.mentionedJid[0] : m.fromMe ? conn.user.jid : m.sender
> let username = conn.getName(who)
> let mentionedJid = [m.sender]
> let name = m.fromMe ? conn.user : conn.contacts[m.sender]
> let users = m.sender
> 
> ```
> conn.reply(m.chat, `Foi detectado um link de *Google* enviado por *${username}*\nDssculpe, mas você será banido deste grupo.`, m)
> ```
> 
> await conn.groupRemove(m.chat, [users])
> }
> handler.tags = ['group']
> handler.customPrefix = /www.google.com//([0-9A-Za-z]{20,24})/i
> handler.command = new RegExp
> handler.group = true
> 
> handler.admin = false
> handler.botAdmin = true
> 
> handler.fail = null
> 
> module.exports = handler

handler.customPrefix = /google.com\/([0-9A-Za-z]{20,24})/i

**Comment by RC047** [comment]
handler.customPrefix = /chat.whatsapp.com\/([0-9A-Za-z]{20,24})/i

> 
> 
> let handler = async function(m, { conn , args, isAdmin, isBotAdmin }) {
> 
> let who = m.mentionedJid && m.mentionedJid[0] ? m.mentionedJid[0] : m.fromMe ? conn.user.jid : m.sender
> let username = conn.getName(who)
> let mentionedJid = [m.sender]
> let name = m.fromMe ? conn.user : conn.contacts[m.sender]
> let users = m.sender
> 
> ```
> conn.reply(m.chat, `Foi detectado um link de *Google* enviado por *${username}*\nDssculpe, mas você será banido deste grupo.`, m)
> ```
> 
> await conn.groupRemove(m.chat, [users])
> }
> handler.tags = ['group']
> handler.customPrefix = /www.google.com//([0-9A-Za-z]{20,24})/i
> handler.command = new RegExp
> handler.group = true
> 
> handler.admin = false
> handler.botAdmin = true
> 
> handler.fail = null
> 
> module.exports = handler

handler.customPrefix = /google.com\/([0-9A-Za-z]{20,24})/i
