### ISSUE TITLE
Bot Error :( Pada Saat pkg update && pkg upgrade

### ISSUE THREAD

**Issue by KazukoGans** [RC047/Kuhong-V4#20]
![Screenshot_2021-04-12-22-47-19](https://user-images.githubusercontent.com/81819581/114414349-4f945480-9be1-11eb-8ac4-9ec143a4e4c9.png)
Itu knp dh:(

**Comment by RC047** [comment]
$ apt update
$ apt upgrade

**Comment by RC047** [comment]
Sebelum update pkg
