### ISSUE TITLE
Cara ganti bailyes baru ke lama

### ISSUE THREAD

**Issue by ghost** [RC047/Kuhong-V4#21]
Gimana gan? Yg baru suka eror klo kirim gambar

**Comment by RC047** [comment]
npm i adiwajshing/baileys^3.4.1

**Comment by ghost** [comment]
> npm i adiwajshing/baileys^3.4.1

![Screenshot_2021-04-14-20-06-33-28](https://user-images.githubusercontent.com/81492529/114715173-fe10d480-9d5c-11eb-87ec-a70e286e9b35.jpg)
Eror gan

**Comment by RC047** [comment]
Coba edit di package.json ganti versi adiwajshingnya jdi 3.4.1 terus save..

Ketik npm i

**Comment by ghost** [comment]
> Coba edit di package.json ganti versi adiwajshingnya jdi 3.4.1 terus save..
> 
> Ketik npm i

Bisa diubah, tapi tetep suka eror kalo kirim gambar hamdeh :(.

**Comment by RC047** [comment]
> > Coba edit di package.json ganti versi adiwajshingnya jdi 3.4.1 terus save..
> > Ketik npm i
> 
> Bisa diubah, tapi tetep suka eror kalo kirim gambar hamdeh :(.

Harus pake sc lama klo biar gk erorr,, yg pake main.js aja gk pake handler.js sama config.js,, kalo gw mah

**Comment by ghost** [comment]
> > > Coba edit di package.json ganti versi adiwajshingnya jdi 3.4.1 terus save..
> > > Ketik npm i
> > 
> > 
> > Bisa diubah, tapi tetep suka eror kalo kirim gambar hamdeh :(.
> 
> Harus pake sc lama klo biar gk erorr,, yg pake main.js aja gk pake handler.js sama config.js,, kalo gw mah

Ada sc yg lama ga gan? Saya ga punya soalnya. Kalau boleh bagi hehe

**Comment by RC047** [comment]
Ga

**Comment by ghost** [comment]
> Ga

:)
