### ISSUE TITLE
Bailleys kenapa?

### ISSUE THREAD

**Issue by ardisuro997** [RC047/Kuhong-V4#22]
Ngab, kirim gambar ga bisa ya? Pas ketik command menu pun kadang error ga muncul kek bailleys tulisan di termux putih gtu, pinterest pun juga jarang bisa, solusi lahh :v

**Comment by RC047** [comment]
Minta fixin ke pembuat baileysnya,, klo mau biar bener lagi,, atau turunin versi baileysnya jdi ke 3.4.1
