### ISSUE TITLE
req fitur

### ISSUE THREAD

**Issue by techwiz37** [RC047/Kuhong-V4#24]
misal download video ig memakai 4 limit, nah kalau download videonya gagal, limitnya ga jdi berkurang.

krna ini download gagal ttp motong limit

**Comment by RC047** [comment]
if (e) global.DATABASE._users.user[m.sender].limit += 1

pake try { kasih dibawahnya

} catch (e) {
  if (e) global.DATABASE._users.user[m.sender].limit += 1

**Comment by techwiz37** [comment]
trus handler.limitnya dibikin true?

**Comment by RC047** [comment]
> trus handler.limitnya dibikin true?

Ya
