### ISSUE TITLE
help

### ISSUE THREAD

**Issue by techwiz37** [RC047/Kuhong-V4#3]
scnya gbsa diapa"kan dicomand #menu #help !menu !help .menu .help /menu /help ga respon, di console log termux chat tsb jg gk kedetect

**Comment by RC047** [comment]
> 
> 
> scnya gbsa diapa"kan dicomand #menu #help !menu !help .menu .help /menu /help ga respon, di console log termux chat tsb jg gk kedetect

Coba ss

**Comment by RC047** [comment]
fixed
