### ISSUE TITLE
Gimana cara biar bisa pinterest search bang

### ISSUE THREAD

**Issue by elssword** [RC047/Kuhong-V4#4]
Pake api fdci bang gimana cara biar bisa search

**Comment by RC047** [comment]
('api.fcdi.se.php?gambar=' + text)

**Comment by elssword** [comment]
Anu bang pas udah selesai hasilnya kan https:\/\/i.pinimg.com\/originals\ nah gara gara ada \/ buffer nya jadi gk bisa

**Comment by elssword** [comment]
Ada\ , /

**Comment by elssword** [comment]
![Screenshot_2021-03-28-18-02-07-541_com termux](https://user-images.githubusercontent.com/48546605/112749948-c6312f80-8fef-11eb-85a9-7c684fe708ab.jpg)
Eror kayak gini bang

**Comment by elssword** [comment]
let fetch = require('node-fetch')

let handler = async(m, { conn, text }) => {
  await m.reply('Searching...')

        fetch('https://api.fdci.se/sosmed/rep.php?gambar=' + text )
            .then(res => res.text())
            .then(body => {
                let randomnime = body.split('\n')
                let randomnimex = randomnime[Math.floor(Math.random() * randomnime.length)]
                conn.sendFile(m.chat, randomnimex, '', text, m)
            })
            .catch(() => {
                conn.reply(m.chat, 'dalam pengembangan', m)
            })
}


Mohon di koreksi bang kalo ada yg salah

**Comment by ardisuro997** [comment]
Bang, kok sc nya di gua ga kedetect sih? Ketik #menu /menu !menu .menu ga respon, di termux nya pun ga kedetect, klo km kok bisa bang?

**Comment by elssword** [comment]
> Bang, kok sc nya di gua ga kedetect sih? Ketik #menu /menu !menu .menu ga respon, di termux nya pun ga kedetect, klo km kok bisa bang?

Coba liat di main.js
global.prefix = new RegExp
Itu daftar prefix yg bisa di pake

**Comment by ardisuro997** [comment]
Udah ku coba semua, coba share no whatsapp nya bang, w mo nanya dahh :v

**Comment by elssword** [comment]
Nanya ke @RC047 aja bang,gk seberapa paham bot nya saya kalo mau tau nomer nya liatbdi reportbug.js wkwk

**Comment by ardisuro997** [comment]
Udh w scan, trus ga ada chat ke detect di termux, trus pas w matiin Ctrl + z, trus w aktifin lagi node index.js malah disuruh scan qr ulang, cara ngatasinya gimana?

**Comment by RC047** [comment]
> 
> 
> let fetch = require('node-fetch')
> 
> let handler = async(m, { conn, text }) => {
> await m.reply('Searching...')
> 
> ```
>     fetch('https://api.fdci.se/sosmed/rep.php?gambar=' + text )
>         .then(res => res.text())
>         .then(body => {
>             let randomnime = body.split('\n')
>             let randomnimex = randomnime[Math.floor(Math.random() * randomnime.length)]
>             conn.sendFile(m.chat, randomnimex, '', text, m)
>         })
>         .catch(() => {
>             conn.reply(m.chat, 'dalam pengembangan', m)
>         })
> ```
> 
> }
> 
> Mohon di koreksi bang kalo ada yg salah



> 
> 
> let fetch = require('node-fetch')
> 
> let handler = async(m, { conn, text }) => {
> await m.reply('Searching...')
> 
> ```
>     fetch('https://api.fdci.se/sosmed/rep.php?gambar=' + text )
>         .then(res => res.text())
>         .then(body => {
>             let randomnime = body.split('\n')
>             let randomnimex = randomnime[Math.floor(Math.random() * randomnime.length)]
>             conn.sendFile(m.chat, randomnimex, '', text, m)
>         })
>         .catch(() => {
>             conn.reply(m.chat, 'dalam pengembangan', m)
>         })
> ```
> 
> }
> 
> Mohon di koreksi bang kalo ada yg salah

let imageToBase64 = require('image-to-base64');
let axios = require("axios");
let handler = async(m, { conn, text }) => {

    if (!text) return conn.reply(m.chat, 'Harap masukan query', m)

    let url = "https://api.fdci.se/rep.php?gambar=" + text;
    let str = `
*Hasil Pencarian :*

${text}
`.trim()

  await m.reply('Searching...')
    axios.get(url)
      .then((result) => {
        let b = JSON.parse(JSON.stringify(result.data));
        let text =  b[Math.floor(Math.random() * b.length)];
        imageToBase64(text) // Path to the image
        .then(
            (response) => {
        let buf = Buffer.from(response, 'base64'); // Ta-da

    conn.sendFile(m.chat, buf, 'foto.jpg', str, m)
            }
        )
        .catch(
            (error) => {
                console.log(error); // Logs an error if there was one
            }
        )

    });
    }
handler.help = ['image <query>','foto <query>']
handler.tags = ['image']
handler.command = /^(image|foto)$/i
handler.owner = false
handler.mods = false
handler.premium = false
handler.group = false
handler.private = false

handler.admin = false
handler.botAdmin = false

handler.fail = null
handler.exp = 0
handler.limit = true

module.exports = handler

**Comment by RC047** [comment]
> 
> 
> Udh w scan, trus ga ada chat ke detect di termux, trus pas w matiin Ctrl + z, trus w aktifin lagi node index.js malah disuruh scan qr ulang, cara ngatasinya gimana?

Iyaa itu versi bot yg lama dh gk bisa dipake,, harus diupdate lagi.

nnti w update :v

**Comment by elssword** [comment]
> > let fetch = require('node-fetch')
> > let handler = async(m, { conn, text }) => {
> > await m.reply('Searching...')
> > ```
> >     fetch('https://api.fdci.se/sosmed/rep.php?gambar=' + text )
> >         .then(res => res.text())
> >         .then(body => {
> >             let randomnime = body.split('\n')
> >             let randomnimex = randomnime[Math.floor(Math.random() * randomnime.length)]
> >             conn.sendFile(m.chat, randomnimex, '', text, m)
> >         })
> >         .catch(() => {
> >             conn.reply(m.chat, 'dalam pengembangan', m)
> >         })
> > ```
> > 
> > 
> > }
> > Mohon di koreksi bang kalo ada yg salah
> 
> > let fetch = require('node-fetch')
> > let handler = async(m, { conn, text }) => {
> > await m.reply('Searching...')
> > ```
> >     fetch('https://api.fdci.se/sosmed/rep.php?gambar=' + text )
> >         .then(res => res.text())
> >         .then(body => {
> >             let randomnime = body.split('\n')
> >             let randomnimex = randomnime[Math.floor(Math.random() * randomnime.length)]
> >             conn.sendFile(m.chat, randomnimex, '', text, m)
> >         })
> >         .catch(() => {
> >             conn.reply(m.chat, 'dalam pengembangan', m)
> >         })
> > ```
> > 
> > 
> > }
> > Mohon di koreksi bang kalo ada yg salah
> 
> let imageToBase64 = require('image-to-base64');
> let axios = require("axios");
> let handler = async(m, { conn, text }) => {
> 
> ```
> if (!text) return conn.reply(m.chat, 'Harap masukan query', m)
> 
> let url = "https://api.fdci.se/rep.php?gambar=" + text;
> let str = `
> ```
> 
> _Hasil Pencarian :_
> 
> ${text}
> `.trim()
> 
> await m.reply('Searching...')
> axios.get(url)
> .then((result) => {
> let b = JSON.parse(JSON.stringify(result.data));
> let text = b[Math.floor(Math.random() * b.length)];
> imageToBase64(text) // Path to the image
> .then(
> (response) => {
> let buf = Buffer.from(response, 'base64'); // Ta-da
> 
> ```
> conn.sendFile(m.chat, buf, 'foto.jpg', str, m)
>         }
>     )
>     .catch(
>         (error) => {
>             console.log(error); // Logs an error if there was one
>         }
>     )
> 
> });
> }
> ```
> 
> handler.help = ['image ','foto ']
> handler.tags = ['image']
> handler.command = /^(image|foto)$/i
> handler.owner = false
> handler.mods = false
> handler.premium = false
> handler.group = false
> handler.private = false
> 
> handler.admin = false
> handler.botAdmin = false
> 
> handler.fail = null
> handler.exp = 0
> handler.limit = true
> 
> module.exports = handler

Thanks bang akhirnya bisa wkwkwk
