### ISSUE TITLE
Bang buatin pencarian judul lewat gambar

### ISSUE THREAD

**Issue by elssword** [RC047/Kuhong-V4#6]
https://trace.moe/api/search

**Comment by RC047** [comment]
Kayak gimana? coba ss

**Comment by elssword** [comment]
![Screenshot_2021-03-29-16-37-21-691_com yowhatsapp](https://user-images.githubusercontent.com/48546605/112817860-1a4e1980-90ad-11eb-9a86-6dd9a54729e9.jpg)
Kayak gitu bang
Jadi kirim gambar sama comand terus bot nya bisa search judul,eps,sama scene yg mirip ama gambar yg dikirim

**Comment by RC047** [comment]
Ohh itu fitur wait(what is anime)

w punya fiturnya tpi nnti aja dh :v

**Comment by elssword** [comment]
Kalo search sumber gambar bisa gk bang
Misal kita kirim gambar cuma gk tau sumber dari mana, terus pake bot bisa tau kalo dari pixiv sama lain lain

**Comment by RC047** [comment]
> 
> 
> Kalo search sumber gambar bisa gk bang
> Misal kita kirim gambar cuma gk tau sumber dari mana, terus pake bot bisa tau kalo dari pixiv sama lain lain

Bisa2 aja klo punya alat website yg bisa ngesearch anime

**Comment by elssword** [comment]
https://app.zenserp.com
Pake web ini bang

**Comment by techwiz37** [comment]
aku ada sourcenya

**Comment by elssword** [comment]
Bagi bang, please

**Comment by CLOEI** [comment]
@elssword simple sih untuk di implementasi-kan mungkin aku bakalan implemen ke bot yang sedang saya buat,
Untuk caranya :  
Post ke url api dengan image dari user berbasis: base64
Lalu, response dari API tinggal dikembalikan ke user

**Comment by elssword** [comment]
> @elssword simple sih untuk di implementasi-kan mungkin aku bakalan implemen ke bot yang sedang saya buat,
> Untuk caranya :
> Post ke url api dengan image dari user berbasis: base64
> Lalu, response dari API tinggal dikembalikan ke user

Tapi kadang hasil nya gk sesuai misal kita kirim gambar dari mana gitu nanti malah ke detect nya judul nya beda

**Comment by CLOEI** [comment]
> > @elssword simple sih untuk di implementasi-kan mungkin aku bakalan implemen ke bot yang sedang saya buat,
> > Untuk caranya :
> > Post ke url api dengan image dari user berbasis: base64
> > Lalu, response dari API tinggal dikembalikan ke user
> 
> Tapi kadang hasil nya gk sesuai misal kita kirim gambar dari mana gitu nanti malah ke detect nya judul nya beda

kagak ada yang 100% sesuai apalagi kalau ada kayak watermark di screenshot videonya persentase akurat mungkin cuman 80% kalau tanpa watermark 90%+ apalagi kalau gk ada subtitle ama sekali haha

**Comment by CLOEI** [comment]
> > @elssword simple sih untuk di implementasi-kan mungkin aku bakalan implemen ke bot yang sedang saya buat,
> > Untuk caranya :
> > Post ke url api dengan image dari user berbasis: base64
> > Lalu, response dari API tinggal dikembalikan ke user
> 
> Tapi kadang hasil nya gk sesuai misal kita kirim gambar dari mana gitu nanti malah ke detect nya judul nya beda

lalu ingat.. ini API untuk ngasih tau judul screenshot frame di ANIMENYA. gak bisa custom fan art atau apalah itu.

**Comment by elssword** [comment]
> > > @elssword simple sih untuk di implementasi-kan mungkin aku bakalan implemen ke bot yang sedang saya buat,
> > > Untuk caranya :
> > > Post ke url api dengan image dari user berbasis: base64
> > > Lalu, response dari API tinggal dikembalikan ke user
> > 
> > 
> > Tapi kadang hasil nya gk sesuai misal kita kirim gambar dari mana gitu nanti malah ke detect nya judul nya beda
> 
> lalu ingat.. ini API untuk ngasih tau judul screenshot frame di ANIMENYA. gak bisa custom fan art atau apalah itu.

Ku kira bisa dari fan art ok bang thanks ya udah bantu
