### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by techwiz37** [RC047/Kuhong-V4#9]
ngechat temen noprefix malah ngerespon gitu
![Screenshot_2021-03-31-15-46-33-778_com whatsapp w4b](https://user-images.githubusercontent.com/73012169/113117305-7ee9af80-9238-11eb-9058-9fec8e99874c.jpg)

**Comment by techwiz37** [comment]
masi banyak bug, di exec.js ada (i) is not defined, di .exp dan .limit tf jg sama eror, dan .buygift itu owner mau buat kode gift dmna?

**Comment by RC047** [comment]
> masi banyak bug, di exec.js ada (i) is not defined, di .exp dan .limit tf jg sama eror, dan .buygift itu owner mau buat kode gift dmna?

Klo mau edit kode gift di gift.js

**Comment by techwiz37** [comment]
nanti fix dlu bug itu ngechat no comand malah respon itu :v

**Comment by techwiz37** [comment]
TypeError: Cannot read property 'exp' of undefined
    at WAConnection.handler (/storage/61AA-18FD/mybotbeta/plugins/exp.js:19:8)
    at WAConnection.handler (/storage/61AA-18FD/mybotbeta/handler.js:187:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by techwiz37** [comment]
ini mah plugins anti firtext ternyata yg bkin eror
